spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  application:
    name:
      backend
    autoconfigure:
      exclude=org:
        springframework:
          boot:
            autoconfigure:
              security:
                servlet:
                  SecurityAutoConfiguration

server:
  port : 8081

telegram:
  bot:
    token:
      12345:mybottesttoken

